[package]
name = "comchan"
version = "0.2.6"
edition = "2021"
authors = ["Vaishnav Sabari Girish forgamesonly684@gmail.com"]
license = "MIT"
description = "A Blazingly Fast and Minimal Serial Monitor for Embedded Applications"
readme = "README.md"
homepage = "https://github.com/Vaishnav-Sabari-Girish/ComChan"
repository = "https://github.com/Vaishnav-Sabari-Girish/ComChan"
keywords = ["cli", "embedded-systems", "serial-communication"]
categories = ["command-line-utilities", "embedded"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
crossterm = "0.27"
ctrlc = "3.4"
dirs = "5.0"
inline_colorization = "0.1.6"
ratatui = "0.26"
serde = { version = "1.0", features = ["derive"] }
serialport = "4.3"
toml = "0.8"
indexmap = "=2.0.0"
plotters = { version = "0.3.5", default-features = false, features = ["svg_backend", "bitmap_backend", "bitmap_encoder", "line_series", "point_series"] }
chrono = "0.4"
